### ISSUE TITLE
Search results found by duplicate value

### ISSUE THREAD

**Issue by pechischev** [lucaong/minisearch#80] opened 2021-02-01 14:45 UTC
I found problem in lib when I tried input duplicate value by value of tag (in a white small box - SC*). I wanted to get an empty result, but no. I think it's a bug.

My current options:
```
const miniSearch = new MiniSearch({
  idField: 'id',
  fields: ['title', 'ticker'],
  storeFields: ['logo_uri', 'title', 'ticker', 'short_description', 'added', 'id'],
  tokenize: (string, _fieldName) => string.split(' '),
})

...

const result = miniSearch.search(searchValue, {
   prefix: true,
   combineWith: 'AND',
})
```

I tried using without options, but the result was wrong.

![image](https://user-images.githubusercontent.com/14825339/106472467-beec1a80-64b3-11eb-9bc0-248e46cec233.png)

**Comment by lucaong** [comment] 2021-02-02 16:40
Hi @pechischev ,
the example you provide seems to work as expected. You are searching for `sc1 sc1 sc1 sc1` with prefix search enabled and combining with AND. This search query will be tokenized as `["sc1", "sc1", "sc1", "sc1"]`.

The `combineWith: 'AND'` won't have an effect here, because the query translates to: "find all results that match `sc1` AND `sc1` AND `sc1` AND `sc1`", which is equivalent to "find all results that match `sc1`".

Therefore it will find all documents that contain terms (in `title` or `ticker`) starting with `sc1`. All the returned results have a ticker that starts in fact with SC1 (**SC1**, **SC1**3, **SC1**4,  **SC1**5, **SC1**6).

What is unexpected to you? Maybe I misunderstood your question, feel free to clarify what the issue is 🙂

**Comment by lucaong** [comment] 2021-02-05 09:23
I will close this issue for now, but feel free to comment on it if your problem is not solved.

**Closed by lucaong** 2021-02-05 09:23 UTC
