### ISSUE TITLE
Prefix search not working

### ISSUE THREAD

**Issue by Thomas-1985** [lucaong/minisearch#171] opened 2022-09-17 20:56 UTC
Hi

package version: 5.0.0

Currently i use minisearch like this
```

const data = [
  {
    "title": "Old Man's War",
    "author": "John Scalzi"
  },
  {
    "title": "The Lock Artist",
    "author": "Steve"
  },
  {
    "title": "Artist for Life",
    "author": "Michelangelo"
  },
  {
    "title": "Artists for Life",
    "author": "Michelangelo"
  }
];

    const searchOptions = {
      combineWith: "OR",
      searchOptions: {
        prefix: true,
        fuzzy: false
      }
    }

    const query = 'Artist';

    const engine = new MiniSearch({
      fields: ['title'],
      searchOptions: searchOptions
      })

    engine.addAll(data);
    const searchResult = engine.search(query);
```

I get a search result if there is the word "Artist" but not i.e. "Artists" . What am i doing wrong here?

Another question, "Awesomeartists" would never match (its not a prefix), or am i wrong?

**Comment by lucaong** [comment] 2022-09-22 10:00
Hi @Thomas-1985 ,
the problem is that you are passing `searchOptions` nested twice. Try this:

```javascript
const searchOptions = {
  combineWith: "OR",
  prefix: true,
  fuzzy: false
}

const engine = new MiniSearch({
  fields: ['title'],
  searchOptions: searchOptions
})
```

Now, prefix match should work.

To your second question, no, `Awesomeartists` (one word) won't match `artist`. For similar terms you can use fuzzy mach, but in this case the two terms are too different.

**Comment by lucaong** [comment] 2022-09-22 13:03
I am going to close this issue, as it should be solved, but feel free to comment further if necessary.

**Closed by lucaong** 2022-09-22 13:03 UTC
