### ISSUE TITLE
Import error on typescript environment

### ISSUE THREAD

**Issue by danielbom** [lucaong/minisearch#53] opened 2020-07-08 18:30 UTC
I'm use:
* node v14.5.0,
* typescript v3.9.6
* ts-node v8.10.2

on a Windows 10 system, and when I only import Minisearch like:

```javascript
import Minisearch from 'minisearch';
```

I get the follow error on try run with ts-node:

```
const searcher = new Minisearch({
                 ^
TypeError: minisearch_1.default is not a constructor
    at Object.<anonymous> (C:\Users\farin\atla\bercario\bot\src\internals\Searcher.ts:8:18)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Module.m._compile (C:\Users\farin\atla\bercario\bot\node_modules\ts-node\src\index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\farin\atla\bercario\bot\node_modules\ts-node\src\index.ts:861:12)       
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
```

Can anyone help me? I'm not know if I'm doing something wrong and I can't imagine how to fix that.

**Comment by lucaong** [comment] 2020-07-08 20:57
I think the problem is that it's `MiniSearch`, not `Minisearch`. Can you try with:

```javascript
import MiniSearch from 'minisearch'
```

Does this solve your issue?

**Comment by danielbom** [comment] 2020-07-08 23:04
I run in my home on Ubuntu System and works both syntaxes (MiniSearch and Minisearch), how I expected from import modules with typescript. I can test tomorrow on Window, because the computer is from my job. But, I think this is not a solution.

**Comment by lucaong** [comment] 2020-07-09 10:09
Then it is most likely an issue with your build environment, but it is very hard to solve it without knowing details about it. I also unfortunately do not own a Windows machine to try to reproduce this.

In general, this does not seem to be an issue related to MiniSearch, so I will close this, but feel free to comment on it and I will reopen it if it turns out to be something that must be fixed in MiniSearch.

**Closed by lucaong** 2020-07-09 10:09 UTC

**Comment by danielbom** [comment] 2020-07-09 11:19
I remove the node_modules and try install again, and works. Thanks.

**Comment by lucaong** [comment] 2020-07-09 11:49
Glad that it worked :)

**Comment by slawiko** [comment] 2021-06-07 12:15
Hello folks,

I just encountered the same issue when I tried to test (using Jest) angular service that operates with MiniSearch library. I was able to fix the issue by substituing my `tsconfig.spec.json` with
