### ISSUE TITLE
Plans for *-search

### ISSUE THREAD

**Issue by MichaelRoger** [lucaong/minisearch#151] opened 2022-04-19 08:27 UTC
Hi,
are there any plans to use scenarios where the user searches for example 'mic*l' oder '*and*'?

thanks

**Comment by lucaong** [comment] 2022-04-20 09:24
Hi @MichaelRoger ,
thanks for your question. So far, there is no plan to support arbitrary wildcard queries, because while in theory it would be feasible, it would still have caveats and in general not be performant.

There are multiple issues at play:

  1. `MiniSearch` design explicitly avoids implementing a query language as strings: if `*` had a special meaning in normal searches, it would have to be escaped when one wants to literally search for `*`, but for most applications that would mean training end users to use a query language, which we cannot assume to be feasible, or escaping the query before passing it to `MiniSearch`, which is not convenient. What `MiniSearch` strives to do, is to provide the building blocks for developers to create such query language layer, in case they need. That's why [query combinations as data structures](https://lucaong.github.io/minisearch/classes/_minisearch_.minisearch.html#advanced-combination-of-queries) are provided.
  2. While we can optimize for prefix match and fuzzy match bounded by edit distance, arbitrary wildcard expressions can easily get very complex, with no hope for optimization with the index implemented as a radix tree. For an application with a big index, some wildcard queries would be complex enough to block the UI. Imagine, for example, searching for `*foo*` would basically amount to traverse the whole index, and at that point it's just as performant as a `documents.filter((doc) => /foo/.test(doc[field]))`. If `MiniSearch` cannot deliver better performance than a brute-force search on a use case, I think it should not support such use case, as it would be misleading for developers.
  3. It could be possible and performant to allow wildcards with some limitations, for example requiring a prefix before the first `*`, like in your `mic*l` example, but that would make the API complex, and it's something that a developer in need of such feature could anyway build by combining prefix search with filtering results using a regular expression.

In sum, I am currently of the opinion that such feature should not be built in `MiniSearch`, because it would add more issues and complexity than it would solve. For completeness, note that [lunr](https://github.com/olivernn/lunr.js/) does provide support for such wildcard queries.

**Comment by MichaelRoger** [comment] 2022-04-20 09:39
Sometimes a usecase is definitly to search "parts of a term".
for example the mentioned "phonenumber-search" the given solution in #130 just massively blows up the index and does not really solve the problem.

**Comment by lucaong** [comment] 2022-04-21 09:40
Yes, that is definitely true. The problem is that `MiniSearch`, with its radix tree index, cannot provide a general performant solution to this particular use case, at least not one that is better than the brute force approach. Some cases can be optimized, such as when there is a prefix before the wildcard (like `foo*`), but many other cannot, like `*foo*`. In other words, `MiniSearch` is not the right tool for arbitrary wildcard searches, so I am of the opinion that implementing an API for that using a brute force approach under the hood would mislead users into misusing `MiniSearch` for a use-case that it is not optimized for.

If searching in the middle of a term is the main use case, the best options are:

  - Use `MiniSearch`, but apply some sort of normalization or custom strategy to make this possible. For example, for phone numbers or other limited-length fields, [this solution](https://github.com/lucaong/minisearch/issues/130#issuecomment-1044773525) outlined in #130 would work well (at the cost of a bigger index size). Often one can also solve it with normalization: for phone numbers, if the goal is not to search arbitrarily any sub string, but rather be able to search with or without international prefix, then one could normalize the number and index it both with and without prefix.
  - Use another library, maybe one with a different data structure for the index. For example, a trigram index would be in general less performant and less precise than `MiniSearch` for prefix search and fuzzy match, but would adapt better to this case of searching in the middle of a term.
  - Implement a custom "brute force" solution, such as turning the search into a regular expression and using it to filter all documents. Of course, this would be slow on large collections, but on small collections it could be a sensible approach.

**Comment by lucaong** [comment] 2022-04-26 20:04
I would close this issue for now, but discussion is welcome.

**Closed by lucaong** 2022-04-26 20:04 UTC
