### ISSUE TITLE
How to return full objects when search criteria has been met (storeFields)?

### ISSUE THREAD

**Issue by Thomas-1985** [lucaong/minisearch#165] opened 2022-07-08 08:32 UTC
Hi

package version: 5.0.0

Currently i use minisearch like this
```

const data = [
  {
    "title": "Old Man's War",
    "author": "John Scalzi"
  },
  {
    "title": "The Lock Artist",
    "author": "Steve"
  },
  {
    "title": "Artist for Life",
    "author": "Michelangelo"
  },
  {
    "title": "Artists for Life",
    "author": "Michelangelo"
  }
];

    const searchOptions = {
      combineWith: "AND",
      searchOptions: {
        prefix: false,
        fuzzy: false
      }
    }

    const query = 'Artist';

    const engine = new MiniSearch({
      fields: ['title'],
      searchOptions: searchOptions
      })

    engine.addAll(data);
    const searchResult = engine.search(query);
```

This works but the problem im facing is that i just getting an array off `null` values back. What i want to achieve is that i get the objects back that match with all properties, and in my real project, i cannot name them since there are so many. So i am looking for something like `storeFields: ALL`

**Comment by lucaong** [comment] 2022-07-08 08:43
Hi @Thomas-1985 ,
`MiniSearch` by design does not store the original documents, for different reasons. The best way to achieve what you want is to keep a mapping of id to document:

```javascript
const data = [
  {
    "id": 1,
    "title": "Old Man's War",
    "author": "John Scalzi"
  },
  {
    "id": 2,
    "title": "The Lock Artist",
    "author": "Steve"
  },
  {
    "id": 3,
    "title": "Artist for Life",
    "author": "Michelangelo"
  },
  {
    "id": 4,
    "title": "Artists for Life",
    "author": "Michelangelo"
  }
]

// Create a mapping of ID to document
const documentById = data.reduce((byId, document) => {
  byId[document.id] = document
  return byId
}, {})

const engine = new MiniSearch({
  fields: ['title'],
  searchOptions: {
    combineWith: "AND",
    fuzzy: false,
    prefix: false
  }
})

engine.addAll(data)

const results = engine.search(query)

// Map search results to documents
const resultDocuments = results.map((result) => documentById[result.id])
```

**Comment by Thomas-1985** [comment] 2022-07-08 19:56
Yes that works, thanks a lot :)

**Comment by lucaong** [comment] 2022-07-09 09:35
Welcome 🙂 I will close the issue for now, but feel free to comment further if needed.

**Closed by lucaong** 2022-07-09 09:35 UTC
