### ISSUE TITLE
How to prevent treating terms separately?

### ISSUE THREAD

**Issue by PuneetKohli** [lucaong/minisearch#244] opened 2024-01-22 08:49 UTC
Hey, so if we give an input such as "Software In" and expect it to return "Software Intern" and "Software Infrastructure Engineer" from search, how do we prevent Minisearch from treating "In" as a term separately, and returning terms that starts with just "In" and doesn't have the word "software" in it?

Is there a flag to always use all the terms?

**Comment by lucaong** [comment] 2024-01-22 09:51
Hi @PuneetKohli ,
yes, you can achieve what you want by using the [search option `combineWith: 'AND'`](https://lucaong.github.io/minisearch/types/MiniSearch.SearchOptions.html). This will require all query terms to be present in the results (retrieving documents that contain both "software" and "in").

```javascript
const documents = [
  { id: 1, text: "Software development" },
  { id: 2, text: "Software Infrastructure" },
  { id: 3, text: "Software Intern" }
]

const miniSearch = new MiniSearch({
  fields: ['text']
})

miniSearch.search("software in", { combineWith: "AND", prefix: true })
// => will return documents 2 and 3
```

Note though that you might get results where the two terms are not contiguous, like "**Software** developed by an **In**dian company". That's because MiniSearch does not take the term position into account (this is by design, as doing so would result in much larger indexes, against the goal of MiniSearch to fit in memory).

It is possible to filter only documents where the query terms appear contiguously, simulating a phrase search, by doing something like:

```javascript
const documents = [
  { id: 1, text: "Software development" },
  { id: 2, text: "Software Infrastructure" },
  { id: 3, text: "Software Intern" },
  { id: 4, text: "Software developed by an Indian company" }
]

const miniSearch = new MiniSearch({
  fields: ['text'],
  storeFields: ['text']
})

const query = "software in"

miniSearch.search(query, {
  combineWith: "AND",
  prefix: true,
  filter: (result) => result.text.toLowerCase().includes(query.toLowerCase())
})
// => will return documents 2 and 3
```

I hope this helps :)

**Comment by lucaong** [comment] 2024-01-26 09:28
@PuneetKohli I think your question was answered, so I am going to close the issue. If you need any more help though, feel free to comment further on this issue.

**Closed by lucaong** 2024-01-26 09:28 UTC
