### ISSUE TITLE
Two character searches always come back blank

### ISSUE THREAD

**Issue by divmgl** [lucaong/minisearch#189] opened 2022-12-15 07:11 UTC
Not much to say here. In two distinct datasets, searching with two characters using fuzzy searching >= 1 will always return an empty array.

**Comment by divmgl** [comment] 2022-12-15 07:12
Switching prefix to `true` seems to make it work as intended.

**Comment by lucaong** [comment] 2022-12-15 10:25
Hi @divmgl ,
I cannot reproduce this, and in fact, if I try a simple example, things work properly:

```javascript
const ms = new MiniSearch({ fields: ['txt'] })
const docs = [{ id: 1, txt: 'f' }, { id: 2, txt: 'fo' }, { id: 3, txt: 'foo' }, { id: 4, txt: 'fox' }]
ms.addAll(docs)
ms.search('fo', { fuzzy: 2 })
/* =>
[
  {
    id: 2,
    score: 1.8059592064889043,
    terms: [ 'fo' ],
    match: { fo: [Array] }
  },
  {
    id: 3,
    score: 0.6095112321900052,
    terms: [ 'foo' ],
    match: { foo: [Array] }
  },
  {
    id: 4,
    score: 0.6095112321900052,
    terms: [ 'fox' ],
    match: { fox: [Array] }
  },
  {
    id: 1,
    score: 0.4063408214600035,
    terms: [ 'f' ],
    match: { f: [Array] }
  }
]
*/
```

Could you provide some example code?

**Comment by lucaong** [comment] 2022-12-21 17:18
Closing this because I cannot reproduce it, and I suspect it is an application issue, but I am happy to reopen it if some reproduction is provided @divmgl

**Closed by lucaong** 2022-12-21 17:18 UTC

**Comment by divmgl** [comment] 2022-12-21 17:32
Here's the repro.

https://stackblitz.com/edit/node-o22erp?file=index.js

Is it user error?

**Comment by divmgl** [comment] 2022-12-21 17:34
Yeah, disregard. It's user error. Thanks.

**Comment by lucaong** [comment] 2022-12-21 22:19
Thanks @divmgl for replying :)
